[package]
name = "printrs"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes", "unstable"] }
colored = "2.0.0"

[profile.release]
panic = "abort"
codegen-units = 1
opt-level = "z"
lto = true